[workspace]
members = ["backend", "backend/runner", "frontend-wasm"]

[workspace.dependencies]
rsground-runner = { path = "./backend/runner" }

actix = "0.13"
actix-cors = "0.7.1"
actix_failwrap = { version = "1.0.3" }
actix-rt = { version = "2.10.0", features = ["macros"] }
actix-web = "4"
actix-ws = "0.3.0"
async-io = "2.4.1"
awc = "3"
bytecount = "0.6"
chrono = "0.4"
console_error_panic_hook = { version = "0.1" }
dotenv = "0.15.0"
env_logger = "0.11.7"
futures = "0.3"
futures-util = "0.3"
hakoniwa = "1.1.0"
js-sys = "0.3"
jsonwebtoken = "8"
lazy_static = "1.4"
log = "0.4"
lsp-types = "0.97.0"
nix = {version = "0.29.0", features = ["process", "signal"]}
oauth2 = { version = "4", features = ["reqwest"] }
once_cell = "1.17"
operational-transform = { version = "0.6", features = ["serde"] }
reqwest = { version = "0.12.15", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
thiserror = "1.0.63"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.16.0", features = ["serde", "v4"] }
wasm-bindgen = "0.2"
