services:
    rsground:
        build:
            context: .
            dockerfile: dev.dockerfile
        ## https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html
##      security_opt:
##          - seccomp:./infra/seccomp.json
##          - apparmor:./infra/non-root-apparmor-profile
##          - no-new-privileges:true
        volumes:
            - ./backend:/app/backend
            - ./frontend:/app/frontend
        ## https://dockerlabs.collabnix.com/advanced/security/capabilities/
##      cap_add: ["DAC_OVERRIDE"]
##      cap_drop: ["ALL"]
        ports:
            - "3000:5173"
        command:
            sh -c "cd frontend && npm run dev &
            cd backend && CARGO_TARGET_DIR='../.backend-output' cargo watch -x run"
        networks:
            - rsground_net

networks:
    rsground_net:
        driver: bridge
