[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-ws = "0.3.0"
chrono = "0.4.38"
futures-util = "0.3.30"
rand = "0.8.5"
reqwest = { version = "0.12.7", features = ["json"] }
serde = "1.0.209"
serde_json = "1.0.127"
shiplift = "0.7.0"
sqlx = { version = "0.8.1", features = ["runtime-tokio-native-tls", "sqlite", "chrono"] }
tokio = { version = "1.39.3", features = ["full"] }
toml = "0.8.19"
urlencoding = "2.1.3"
