[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rsground-runner.workspace = true

chrono.workspace = true
dotenv.workspace = true
env_logger.workspace = true
futures.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

# Auth
jsonwebtoken.workspace = true
oauth2.workspace = true
reqwest.workspace = true
uuid.workspace = true

# Http server
actix.workspace = true
actix-cors.workspace = true
actix_error_proc.workspace = true
actix-web.workspace = true
actix-ws.workspace = true

# Edit Sync
bytecount.workspace = true
operational-transform.workspace = true

[dev-dependencies]
awc.workspace = true
actix-rt.workspace = true
futures-util.workspace = true
lazy_static.workspace = true
once_cell.workspace = true
