services:
  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: ../frontend
      dockerfile: ../infra/images/fe.prod.Dockerfile
    restart: unless-stopped
    ports:
      - 5173:5173

  backend:
    container_name: backend
    env_file:
      - ../backend/.env
    build:
      context: ../backend
      dockerfile: ../infra/images/be.prod.Dockerfile
      args:
        DB: "sqlite://data.db"
    restart: unless-stopped
    ports:
      - 5174:5174
