services:
  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: ../frontend
      dockerfile: ../infra/images/fe.Dockerfile
    volumes:
      - ../frontend:/frontend
    command: npm run dev
    restart: unless-stopped
    ports:
      - 5173:5173

  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: ../infra/images/be.dev.Dockerfile
    volumes:
      - ../backend:/backend
    command: sh -c "cargo watch -x run"
    restart: unless-stopped
    ports:
      - 5174:5174