[package]
name = "frontend-wasm"
version = "0.1.0"
authors = []
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# OT
bytecount.workspace = true
operational-transform.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true

# Wasm
console_error_panic_hook.workspace = true
wasm-bindgen.workspace = true
js-sys.workspace = true
